name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        id: abc
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: r"^ic\\("
          replace: " "
      - name: Find and Replace icecreame
        id: abc_icecreame
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "icecreame"
          replace: " "
          regex: false
      - name: check
        run: |
          echo ${{ steps.abc.outputs.modifiedFiles}}
          echo ${{ steps.abc_icecreame.outputs.modifiedFiles}}
          if [[ ${{ steps.abc.outputs.modifiedFiles}} == '0' ]]; then
            echo "OK..."
          else
            echo "ERR..."
            exit 2
          fi
