name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        id: abc
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ic("
          replace: "world"
          regex: false
      - name: check
        run: |
          echo ${{ steps.abc.outputs.modifiedFiles}}
          if [[ ${{ steps.abc.outputs.modifiedFiles}} == '3' ]]; then
            echo "Abort"
            exit 2
          else
            echo "OK..."
          fi
