name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        id: abc
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "hello"
          replace: "world"
          regex: false
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
