name: My Workflow
on: [push]
jobs:
  check_ic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        id: abc_ic
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "( |\\t|^)ic\\("
          replace: " "
          exclude: ".github/**"
      - name: Find and Replace icecreame
        id: abc_icecreame
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "from icecream"
          replace: " "
          exclude: ".github/**, book"
          regex: false
      - name: check
        run: |
          if [[ ${{ steps.abc_ic.outputs.modifiedFiles}} == '0' ]]; then
            echo "OK..."
          else
            echo "ERR... found ic in code"
            exit 2
          fi
          if [[ ${{ steps.abc_icecreame.outputs.modifiedFiles}} == '0' ]]; then
            echo "OK..."
          else
            echo "ERR... found from icecream in code"
            exit 2
          fi
